### ISSUE TITLE
训练模型

### ISSUE THREAD

**Issue by ideal1213123** [lyg09270/CyberryPotter_ElectromagicWand_Basic_Project#3]
1，clone到本地后是否需要自己重新训练模型,还是安装方式跟up相同就可以直接使用。
2，模型如何训练，安装好python环境后直接运行CNN下的py文件即可？有无先后顺序，其他额外的配置等。

**Comment by lyg09270** [comment]
可以不训练模型直接从Keil中编译工程，我已经训练好了一个模型，如果需要自己重新训练，则可以配置Python环境后进行训练 重新训练可以直接运行训练脚本，也可以自己使用脚本录制动作，然后再进行训练，详细的可以看我b站的视频，简介中有链接
